[package]
name = "hamsteroid"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.8"
# bevy_rapier2d = "0.16"
bevy_rapier3d = "0.16"
bevy_prototype_lyon = "0.6"
bevy_flycam = "*"
bevy-inspector-egui = "0.12"